/*
* Copyright (c) 2021 PSPACE, inc. KSAN Development Team ksan@pspace.co.kr
* KSAN is a suite of free software: you can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation, either version 
* 3 of the License.  See LICENSE for details
*
* 본 프로그램 및 관련 소스코드, 문서 등 모든 자료는 있는 그대로 제공이 됩니다.
* KSAN 프로젝트의 개발자 및 개발사는 이 프로그램을 사용한 결과에 따른 어떠한 책임도 지지 않습니다.
* KSAN 개발팀은 사전 공지, 허락, 동의 없이 KSAN 개발에 관련된 모든 결과물에 대한 LICENSE 방식을 변경 할 권리가 있습니다.
*/
export interface IanaTimezone {
	group: string;
	timezone: string;
	text: string;
}

export const IANA_TIMEZONES = [
	// UTC+14:00
	{ group: 'UTC+14:00', timezone: 'Pacific/Kiritimati', text: 'Pacific/Kiritimati (+14)' },
	// UTC+13:00
	{ group: 'UTC+13:00', timezone: 'Pacific/Apia', text: 'Pacific/Apia (+13)' },
	{ group: 'UTC+13:00', timezone: 'Pacific/Enderbury', text: 'Pacific/Enderbury (+13)' },
	{ group: 'UTC+13:00', timezone: 'Pacific/Fakaofo', text: 'Pacific/Fakaofo (+13)' },
	{ group: 'UTC+13:00', timezone: 'Pacific/Tongatapu', text: 'Pacific/Tongatapu (+13)' },
	// UTC+12:45
	{ group: 'UTC+12:45', timezone: 'Pacific/Chatham', text: 'Pacific/Chatham (+12:45)' },
	// UTC+12:00
	{ group: 'UTC+12:00', timezone: 'Antarctica/McMurdo', text: 'Antarctica/McMurdo (NZST)' },
	{ group: 'UTC+12:00', timezone: 'Asia/Anadyr', text: 'Asia/Anadyr (+12)' },
	{ group: 'UTC+12:00', timezone: 'Asia/Kamchatka', text: 'Asia/Kamchatka (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Auckland', text: 'Pacific/Auckland (NZST)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Fiji', text: 'Pacific/Fiji (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Funafuti', text: 'Pacific/Funafuti (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Kwajalein', text: 'Pacific/Kwajalein (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Majuro', text: 'Pacific/Majuro (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Nauru', text: 'Pacific/Nauru (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Tarawa', text: 'Pacific/Tarawa (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Wake', text: 'Pacific/Wake (+12)' },
	{ group: 'UTC+12:00', timezone: 'Pacific/Wallis', text: 'Pacific/Wallis (+12)' },
	// UTC+11:00
	{ group: 'UTC+11:00', timezone: 'Antarctica/Casey', text: 'Antarctica/Casey (+11)' },
	{ group: 'UTC+11:00', timezone: 'Antarctica/Macquarie', text: 'Antarctica/Macquarie (+11)' },
	{ group: 'UTC+11:00', timezone: 'Asia/Magadan', text: 'Asia/Magadan (+11)' },
	{ group: 'UTC+11:00', timezone: 'Asia/Sakhalin', text: 'Asia/Sakhalin (+11)' },
	{ group: 'UTC+11:00', timezone: 'Asia/Srednekolymsk', text: 'Asia/Srednekolymsk (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Bougainville', text: 'Pacific/Bougainville (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Efate', text: 'Pacific/Efate (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Guadalcanal', text: 'Pacific/Guadalcanal (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Kosrae', text: 'Pacific/Kosrae (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Norfolk', text: 'Pacific/Norfolk (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Noumea', text: 'Pacific/Noumea (+11)' },
	{ group: 'UTC+11:00', timezone: 'Pacific/Pohnpei', text: 'Pacific/Pohnpei (+11)' },
	// UTC+10:30
	{ group: 'UTC+10:30', timezone: 'Australia/Lord_Howe', text: 'Australia/Lord Howe (+10:30)' },
	// UTC+10:00
	{ group: 'UTC+10:00', timezone: 'Antarctica/DumontDUrville', text: 'Antarctica/DumontDUrville (+10)' },
	{ group: 'UTC+10:00', timezone: 'Asia/Ust-Nera', text: 'Asia/Ust-Nera (+10)' },
	{ group: 'UTC+10:00', timezone: 'Asia/Vladivostok', text: 'Asia/Vladivostok (+10)' },
	{ group: 'UTC+10:00', timezone: 'Australia/Brisbane', text: 'Australia/Brisbane (AEST)' },
	{ group: 'UTC+10:00', timezone: 'Australia/Currie', text: 'Australia/Currie (AEST)' },
	{ group: 'UTC+10:00', timezone: 'Australia/Hobart', text: 'Australia/Hobart (AEST)' },
	{ group: 'UTC+10:00', timezone: 'Australia/Lindeman', text: 'Australia/Lindeman (AEST)' },
	{ group: 'UTC+10:00', timezone: 'Australia/Melbourne', text: 'Australia/Melbourne (AEST)' },
	{ group: 'UTC+10:00', timezone: 'Australia/Sydney', text: 'Australia/Sydney (AEST)' },
	{ group: 'UTC+10:00', timezone: 'Pacific/Chuuk', text: 'Pacific/Chuuk (+10)' },
	{ group: 'UTC+10:00', timezone: 'Pacific/Guam', text: 'Pacific/Guam (ChST)' },
	{ group: 'UTC+10:00', timezone: 'Pacific/Port_Moresby', text: 'Pacific/Port Moresby (+10)' },
	{ group: 'UTC+10:00', timezone: 'Pacific/Saipan', text: 'Pacific/Saipan (ChST)' },
	// UTC+09:30
	{ group: 'UTC+09:30', timezone: 'Australia/Adelaide', text: 'Australia/Adelaide (ACST)' },
	{ group: 'UTC+09:30', timezone: 'Australia/Broken_Hill', text: 'Australia/Broken Hill (ACST)' },
	{ group: 'UTC+09:30', timezone: 'Australia/Darwin', text: 'Australia/Darwin (ACST)' },
	// UTC+09:00
	{ group: 'UTC+09:00', timezone: 'Asia/Chita', text: 'Asia/Chita (+09)' },
	{ group: 'UTC+09:00', timezone: 'Asia/Dili', text: 'Asia/Dili (+09)' },
	{ group: 'UTC+09:00', timezone: 'Asia/Jayapura', text: 'Asia/Jayapura (WIT)' },
	{ group: 'UTC+09:00', timezone: 'Asia/Khandyga', text: 'Asia/Khandyga (+09)' },
	{ group: 'UTC+09:00', timezone: 'Asia/Seoul', text: 'Asia/Seoul (KST)' },
	{ group: 'UTC+09:00', timezone: 'Asia/Tokyo', text: 'Asia/Tokyo (JST)' },
	{ group: 'UTC+09:00', timezone: 'Asia/Yakutsk', text: 'Asia/Yakutsk (+09)' },
	{ group: 'UTC+09:00', timezone: 'Pacific/Palau', text: 'Pacific/Palau (+09)' },
	// UTC+08:45
	{ group: 'UTC+08:45', timezone: 'Australia/Eucla', text: 'Australia/Eucla (+08:45)' },
	// UTC+08:30
	{ group: 'UTC+08:30', timezone: 'Asia/Pyongyang', text: 'Asia/Pyongyang (KST)' },
	// UTC+08:00
	{ group: 'UTC+08:00', timezone: 'Asia/Brunei', text: 'Asia/Brunei (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Choibalsan', text: 'Asia/Choibalsan (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Hong_Kong', text: 'Asia/Hong Kong (HKT)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Irkutsk', text: 'Asia/Irkutsk (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Kuala_Lumpur', text: 'Asia/Kuala Lumpur (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Kuching', text: 'Asia/Kuching (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Macau', text: 'Asia/Macau (CST)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Makassar', text: 'Asia/Makassar (WITA)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Manila', text: 'Asia/Manila (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Shanghai', text: 'Asia/Shanghai (CST)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Singapore', text: 'Asia/Singapore (+08)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Taipei', text: 'Asia/Taipei (CST)' },
	{ group: 'UTC+08:00', timezone: 'Asia/Ulaanbaatar', text: 'Asia/Ulaanbaatar (+08)' },
	{ group: 'UTC+08:00', timezone: 'Australia/Perth', text: 'Australia/Perth (AWST)' },
	// UTC+07:00
	{ group: 'UTC+07:00', timezone: 'Antarctica/Davis', text: 'Antarctica/Davis (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Bangkok', text: 'Asia/Bangkok (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Barnaul', text: 'Asia/Barnaul (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Ho_Chi_Minh', text: 'Asia/Ho Chi Minh (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Hovd', text: 'Asia/Hovd (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Jakarta', text: 'Asia/Jakarta (WIB)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Krasnoyarsk', text: 'Asia/Krasnoyarsk (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Novokuznetsk', text: 'Asia/Novokuznetsk (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Novosibirsk', text: 'Asia/Novosibirsk (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Phnom_Penh', text: 'Asia/Phnom_Penh (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Pontianak', text: 'Asia/Pontianak (WIB)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Tomsk', text: 'Asia/Tomsk (+07)' },
	{ group: 'UTC+07:00', timezone: 'Asia/Vientiane', text: 'Asia/Vientiane (+07)' },
	{ group: 'UTC+07:00', timezone: 'Indian/Christmas', text: 'Indian/Christmas (+07)' },
	// UTC+06:30
	{ group: 'UTC+06:30', timezone: 'Asia/Yangon', text: 'Asia/Yangon (+06:30)' },
	{ group: 'UTC+06:30', timezone: 'Indian/Cocos', text: 'Indian/Cocos (+06:30)' },
	// UTC+06:00
	{ group: 'UTC+06:00', timezone: 'Antarctica/Vostok', text: 'Antarctica/Vostok (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Almaty', text: 'Asia/Almaty (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Bishkek', text: 'Asia/Bishkek (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Dhaka', text: 'Asia/Dhaka (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Omsk', text: 'Asia/Omsk (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Qyzylorda', text: 'Asia/Qyzylorda (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Thimphu', text: 'Asia/Thimphu (+06)' },
	{ group: 'UTC+06:00', timezone: 'Asia/Urumqi', text: 'Asia/Urumqi (+06)' },
	{ group: 'UTC+06:00', timezone: 'Indian/Chagos', text: 'Indian/Chagos (+06)' },
	// UTC+05:45
	{ group: 'UTC+05:45', timezone: 'Asia/Kathmandu', text: 'Asia/Kathmandu (+05:45)' },
	// UTC+05:30
	{ group: 'UTC+05:30', timezone: 'Asia/Colombo', text: 'Asia/Colombo (+05:30)' },
	{ group: 'UTC+05:30', timezone: 'Asia/Kolkata', text: 'Asia/Kolkata (IST)' },
	// UTC+05:00
	{ group: 'UTC+05:00', timezone: 'Antarctica/Mawson', text: 'Antarctica/Mawson (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Aqtau', text: 'Asia/Aqtau (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Aqtobe', text: 'Asia/Aqtobe (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Ashgabat', text: 'Asia/Ashgabat (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Atyrau', text: 'Asia/Atyrau (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Dushanbe', text: 'Asia/Dushanbe (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Karachi', text: 'Asia/Karachi (PKT)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Oral', text: 'Asia/Oral (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Samarkand', text: 'Asia/Samarkand (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Tashkent', text: 'Asia/Tashkent (+05)' },
	{ group: 'UTC+05:00', timezone: 'Asia/Yekaterinburg', text: 'Asia/Yekaterinburg (+05)' },
	{ group: 'UTC+05:00', timezone: 'Indian/Kerguelen', text: 'Indian/Kerguelen (+05)' },
	{ group: 'UTC+05:00', timezone: 'Indian/Maldives', text: 'Indian/Maldives (+05)' },
	// UTC+04:30
	{ group: 'UTC+04:30', timezone: 'Asia/Kabul', text: 'Asia/Kabul (+04:30)' },
	{ group: 'UTC+04:30', timezone: 'Asia/Tehran', text: 'Asia/Tehran (+04:30)' },
	// UTC+04:00
	{ group: 'UTC+04:00', timezone: 'Asia/Baku', text: 'Asia/Baku (+04)' },
	{ group: 'UTC+04:00', timezone: 'Asia/Dubai', text: 'Asia/Dubai (+04)' },
	{ group: 'UTC+04:00', timezone: 'Asia/Muscat', text: 'Asia/Muscat (+04)' },
	{ group: 'UTC+04:00', timezone: 'Asia/Tbilisi', text: 'Asia/Tbilisi (+04)' },
	{ group: 'UTC+04:00', timezone: 'Asia/Yerevan', text: 'Asia/Yerevan (+04)' },
	{ group: 'UTC+04:00', timezone: 'Europe/Astrakhan', text: 'Europe/Astrakhan (+04)' },
	{ group: 'UTC+04:00', timezone: 'Europe/Samara', text: 'Europe/Samara (+04)' },
	{ group: 'UTC+04:00', timezone: 'Europe/Saratov', text: 'Europe/Saratov (+04)' },
	{ group: 'UTC+04:00', timezone: 'Europe/Ulyanovsk', text: 'Europe/Ulyanovsk (+04)' },
	{ group: 'UTC+04:00', timezone: 'Indian/Mahe', text: 'Indian/Mahe (+04)' },
	{ group: 'UTC+04:00', timezone: 'Indian/Mauritius', text: 'Indian/Mauritius (+04)' },
	{ group: 'UTC+04:00', timezone: 'Indian/Reunion', text: 'Indian/Reunion (+04)' },
	// UTC+03:00
	{ group: 'UTC+03:00', timezone: 'Africa/Addis_Ababa', text: 'Africa/Addis Ababa (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Asmara', text: 'Africa/Asmara (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Dar_es_Salaam', text: 'Africa/Dar es Salaam (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Djibouti', text: 'Africa/Djibouti (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Juba', text: 'Africa/Juba (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Kampala', text: 'Africa/Kampala (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Khartoum', text: 'Africa/Khartoum (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Mogadishu', text: 'Africa/Mogadishu (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Africa/Nairobi', text: 'Africa/Nairobi (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Antarctica/Syowa', text: 'Antarctica/Syowa (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Aden', text: 'Asia/Aden (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Amman', text: 'Asia/Amman (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Baghdad', text: 'Asia/Baghdad (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Bahrain', text: 'Asia/Bahrain (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Beirut', text: 'Asia/Beirut (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Damascus', text: 'Asia/Damascus (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Famagusta', text: 'Asia/Famagusta (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Gaza', text: 'Asia/Gaza (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Hebron', text: 'Asia/Hebron (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Jerusalem', text: 'Asia/Jerusalem (IDT)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Kuwait', text: 'Asia/Kuwait (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Nicosia', text: 'Asia/Nicosia (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Qatar', text: 'Asia/Qatar (+03)' },
	{ group: 'UTC+03:00', timezone: 'Asia/Riyadh', text: 'Asia/Riyadh (+03)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Athens', text: 'Europe/Athens (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Bucharest', text: 'Europe/Bucharest (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Chisinau', text: 'Europe/Chisinau (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Helsinki', text: 'Europe/Helsinki (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Istanbul', text: 'Europe/Istanbul (+03)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Kiev', text: 'Europe/Kiev (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Kirov', text: 'Europe/Kirov (+03)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Mariehamn', text: 'Europe/Mariehamn (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Minsk', text: 'Europe/Minsk (+03)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Moscow', text: 'Europe/Moscow (MSK)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Riga', text: 'Europe/Riga (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Simferopol', text: 'Europe/Simferopol (MSK)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Sofia', text: 'Europe/Sofia (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Tallinn', text: 'Europe/Tallinn (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Uzhgorod', text: 'Europe/Uzhgorod (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Vilnius', text: 'Europe/Vilnius (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Volgograd', text: 'Europe/Volgograd (+03)' },
	{ group: 'UTC+03:00', timezone: 'Europe/Zaporozhye', text: 'Europe/Zaporozhye (EEST)' },
	{ group: 'UTC+03:00', timezone: 'Indian/Antananarivo', text: 'Indian/Antananarivo (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Indian/Comoro', text: 'Indian/Comoro (EAT)' },
	{ group: 'UTC+03:00', timezone: 'Indian/Mayotte', text: 'Indian/Mayotte (EAT)' },
	// UTC+02:00
	{ group: 'UTC+02:00', timezone: 'Africa/Blantyre', text: 'Africa/Blantyre (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Bujumbura', text: 'Africa/Bujumbura (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Cairo', text: 'Africa/Cairo (EET)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Ceuta', text: 'Africa/Ceuta (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Gaborone', text: 'Africa/Gaborone (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Harare', text: 'Africa/Harare (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Johannesburg', text: 'Africa/Johannesburg (SAST)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Kigali', text: 'Africa/Kigali (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Lubumbashi', text: 'Africa/Lubumbashi (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Lusaka', text: 'Africa/Lusaka (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Maputo', text: 'Africa/Maputo (CAT)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Maseru', text: 'Africa/Maseru (SAST)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Mbabane', text: 'Africa/Mbabane (SAST)' },
	{ group: 'UTC+02:00', timezone: 'Africa/Tripoli', text: 'Africa/Tripoli (EET)' },
	{ group: 'UTC+02:00', timezone: 'Antarctica/Troll', text: 'Antarctica/Troll (+02)' },
	{ group: 'UTC+02:00', timezone: 'Arctic/Longyearbyen', text: 'Arctic/Longyearbyen (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Amsterdam', text: 'Europe/Amsterdam (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Andorra', text: 'Europe/Andorra (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Belgrade', text: 'Europe/Belgrade (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Berlin', text: 'Europe/Berlin (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Bratislava', text: 'Europe/Bratislava (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Brussels', text: 'Europe/Brussels (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Budapest', text: 'Europe/Budapest (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Busingen', text: 'Europe/Busingen (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Copenhagen', text: 'Europe/Copenhagen (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Gibraltar', text: 'Europe/Gibraltar (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Kaliningrad', text: 'Europe/Kaliningrad (EET)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Ljubljana', text: 'Europe/Ljubljana (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Luxembourg', text: 'Europe/Luxembourg (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Madrid', text: 'Europe/Madrid (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Malta', text: 'Europe/Malta (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Monaco', text: 'Europe/Monaco (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Oslo', text: 'Europe/Oslo (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Paris', text: 'Europe/Paris (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Podgorica', text: 'Europe/Podgorica (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Prague', text: 'Europe/Prague (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Rome', text: 'Europe/Rome (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/San_Marino', text: 'Europe/San Marino (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Sarajevo', text: 'Europe/Sarajevo (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Skopje', text: 'Europe/Skopje (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Stockholm', text: 'Europe/Stockholm (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Tirane', text: 'Europe/Tirane (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Vaduz', text: 'Europe/Vaduz (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Vatican', text: 'Europe/Vatican (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Vienna', text: 'Europe/Vienna (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Warsaw', text: 'Europe/Warsaw (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Zagreb', text: 'Europe/Zagreb (CEST)' },
	{ group: 'UTC+02:00', timezone: 'Europe/Zurich', text: 'Europe/Zurich (CEST)' },
	// UTC+01:00
	{ group: 'UTC+01:00', timezone: 'Africa/Algiers', text: 'Africa/Algiers (CET)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Bangui', text: 'Africa/Bangui (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Brazzaville', text: 'Africa/Brazzaville (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Casablanca', text: 'Africa/Casablanca (WEST)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Douala', text: 'Africa/Douala (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/El_Aaiun', text: 'Africa/El Aaiun (WEST)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Kinshasa', text: 'Africa/Kinshasa (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Lagos', text: 'Africa/Lagos (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Libreville', text: 'Africa/Libreville (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Luanda', text: 'Africa/Luanda (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Malabo', text: 'Africa/Malabo (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Ndjamena', text: 'Africa/Ndjamena (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Niamey', text: 'Africa/Niamey (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Porto-Novo', text: 'Africa/Porto-Novo (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Tunis', text: 'Africa/Tunis (CET)' },
	{ group: 'UTC+01:00', timezone: 'Africa/Windhoek', text: 'Africa/Windhoek (WAT)' },
	{ group: 'UTC+01:00', timezone: 'Atlantic/Canary', text: 'Atlantic/Canary (WEST)' },
	{ group: 'UTC+01:00', timezone: 'Atlantic/Faroe', text: 'Atlantic/Faroe (WEST)' },
	{ group: 'UTC+01:00', timezone: 'Atlantic/Madeira', text: 'Atlantic/Madeira (WEST)' },
	{ group: 'UTC+01:00', timezone: 'Europe/Dublin', text: 'Europe/Dublin (IST)' },
	{ group: 'UTC+01:00', timezone: 'Europe/Guernsey', text: 'Europe/Guernsey (BST)' },
	{ group: 'UTC+01:00', timezone: 'Europe/Isle_of_Man', text: 'Europe/Isle of Man (BST)' },
	{ group: 'UTC+01:00', timezone: 'Europe/Jersey', text: 'Europe/Jersey (BST)' },
	{ group: 'UTC+01:00', timezone: 'Europe/Lisbon', text: 'Europe/Lisbon (WEST)' },
	{ group: 'UTC+01:00', timezone: 'Europe/London', text: 'Europe/London (BST)' },
	// UTC
	{ group: 'UTC', timezone: 'Africa/Abidjan', text: 'Africa/Abidjan (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Accra', text: 'Africa/Accra (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Bamako', text: 'Africa/Bamako (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Banjul', text: 'Africa/Banjul (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Bissau', text: 'Africa/Bissau (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Conakry', text: 'Africa/Conakry (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Dakar', text: 'Africa/Dakar (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Freetown', text: 'Africa/Freetown (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Lome', text: 'Africa/Lome (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Monrovia', text: 'Africa/Monrovia (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Nouakchott', text: 'Africa/Nouakchott (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Ouagadougou', text: 'Africa/Ouagadougou (GMT)' },
	{ group: 'UTC', timezone: 'Africa/Sao_Tome', text: 'Africa/Sao_Tome (GMT)' },
	{ group: 'UTC', timezone: 'America/Danmarkshavn', text: 'America/Danmarkshavn (GMT)' },
	{ group: 'UTC', timezone: 'America/Scoresbysund', text: 'America/Scoresbysund (+00)' },
	{ group: 'UTC', timezone: 'Atlantic/Azores', text: 'Atlantic/Azores (+00)' },
	{ group: 'UTC', timezone: 'Atlantic/Reykjavik', text: 'Atlantic/Reykjavik (GMT)' },
	{ group: 'UTC', timezone: 'Atlantic/St_Helena', text: 'Atlantic/St_Helena (GMT)' },
	{ group: 'UTC', timezone: 'UTC', text: 'UTC (UTC)' },
	// UTC-01:00
	{ group: 'UTC-01:00', timezone: 'Atlantic/Cape_Verde', text: 'Atlantic/Cape Verde (-01)' },
	// UTC-02:00
	{ group: 'UTC-02:00', timezone: 'America/Godthab', text: 'America/Godthab (-02)' },
	{ group: 'UTC-02:00', timezone: 'America/Miquelon', text: 'America/Miquelon (-02)' },
	{ group: 'UTC-02:00', timezone: 'America/Noronha', text: 'America/Noronha (-02)' },
	{ group: 'UTC-02:00', timezone: 'Atlantic/South_Georgia', text: 'Atlantic/South Georgia (-02)' },
	// UTC-02:30
	{ group: 'UTC-02:30', timezone: 'America/St_Johns', text: 'America/St Johns (NDT)' },
	// UTC-03:00
	{ group: 'UTC-03:00', timezone: 'America/Araguaina', text: 'America/Araguaina (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Buenos_Aires', text: 'America/Argentina/Buenos Aires (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Catamarca', text: 'America/Argentina/Catamarca (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Cordoba', text: 'America/Argentina/Cordoba (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Jujuy', text: 'America/Argentina/Jujuy (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/La_Rioja', text: 'America/Argentina/La Rioja (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Mendoza', text: 'America/Argentina/Mendoza (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Rio_Gallegos', text: 'America/Argentina/Rio Gallegos (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Salta', text: 'America/Argentina/Salta (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/San_Juan', text: 'America/Argentina/San Juan (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/San_Luis', text: 'America/Argentina/San Luis (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Tucuman', text: 'America/Argentina/Tucuman (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Argentina/Ushuaia', text: 'America/Argentina/Ushuaia (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Bahia', text: 'America/Bahia (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Belem', text: 'America/Belem (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Cayenne', text: 'America/Cayenne (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Fortaleza', text: 'America/Fortaleza (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Glace_Bay', text: 'America/Glace_Bay (ADT)' },
	{ group: 'UTC-03:00', timezone: 'America/Goose_Bay', text: 'America/Goose_Bay (ADT)' },
	{ group: 'UTC-03:00', timezone: 'America/Halifax', text: 'America/Halifax (ADT)' },
	{ group: 'UTC-03:00', timezone: 'America/Maceio', text: 'America/Maceio (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Moncton', text: 'America/Moncton (ADT)' },
	{ group: 'UTC-03:00', timezone: 'America/Montevideo', text: 'America/Montevideo (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Paramaribo', text: 'America/Paramaribo (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Punta_Arenas', text: 'America/Punta Arenas (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Recife', text: 'America/Recife (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Santarem', text: 'America/Santarem (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Sao_Paulo', text: 'America/Sao Paulo (-03)' },
	{ group: 'UTC-03:00', timezone: 'America/Thule', text: 'America/Thule (ADT)' },
	{ group: 'UTC-03:00', timezone: 'Antarctica/Palmer', text: 'Antarctica/Palmer (-03)' },
	{ group: 'UTC-03:00', timezone: 'Antarctica/Rothera', text: 'Antarctica/Rothera (-03)' },
	{ group: 'UTC-03:00', timezone: 'Atlantic/Bermuda', text: 'Atlantic/Bermuda (ADT)' },
	{ group: 'UTC-03:00', timezone: 'Atlantic/Stanley', text: 'Atlantic/Stanley (-03)' },
	// UTC-04:00
	{ group: 'UTC-04:00', timezone: 'America/Anguilla', text: 'America/Anguilla (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Antigua', text: 'America/Antigua (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Aruba', text: 'America/Aruba (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Asuncion', text: 'America/Asuncion (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Barbados', text: 'America/Barbados (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Blanc-Sablon', text: 'America/Blanc-Sablon (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Boa_Vista', text: 'America/Boa Vista (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Campo_Grande', text: 'America/Campo Grande (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Caracas', text: 'America/Caracas (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Cuiaba', text: 'America/Cuiaba (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Curacao', text: 'America/Curacao (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Detroit', text: 'America/Detroit (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Dominica', text: 'America/Dominica (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Grand_Turk', text: 'America/Grand Turk (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Grenada', text: 'America/Grenada (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Guadeloupe', text: 'America/Guadeloupe (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Guyana', text: 'America/Guyana (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Havana', text: 'America/Havana (CDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Indiana/Indianapolis', text: 'America/Indiana/Indianapolis (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Indiana/Marengo', text: 'America/Indiana/Marengo (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Indiana/Petersburg', text: 'America/Indiana/Petersburg (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Indiana/Vevay', text: 'America/Indiana/Vevay (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Indiana/Vincennes', text: 'America/Indiana/Vincennes (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Indiana/Winamac', text: 'America/Indiana/Winamac (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Iqaluit', text: 'America/Iqaluit (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Kentucky/Louisville', text: 'America/Kentucky/Louisville (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Kentucky/Monticello', text: 'America/Kentucky/Monticello (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Kralendijk', text: 'America/Kralendijk (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/La_Paz', text: 'America/La_Paz (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Lower_Princes', text: 'America/Lower Princes (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Manaus', text: 'America/Manaus (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Marigot', text: 'America/Marigot (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Martinique', text: 'America/Martinique (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Montserrat', text: 'America/Montserrat (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Nassau', text: 'America/Nassau (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/New_York', text: 'America/New_York (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Nipigon', text: 'America/Nipigon (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Pangnirtung', text: 'America/Pangnirtung (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Port-au-Prince', text: 'America/Port-au-Prince (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Port_of_Spain', text: 'America/Port of Spain (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Porto_Velho', text: 'America/Porto Velho (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Puerto_Rico', text: 'America/Puerto Rico (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Santiago', text: 'America/Santiago (-04)' },
	{ group: 'UTC-04:00', timezone: 'America/Santo_Domingo', text: 'America/Santo Domingo (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/St_Barthelemy', text: 'America/St Barthelemy (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/St_Kitts', text: 'America/St Kitts (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/St_Lucia', text: 'America/St Lucia (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/St_Thomas', text: 'America/St Thomas (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/St_Vincent', text: 'America/St Vincent (AST)' },
	{ group: 'UTC-04:00', timezone: 'America/Thunder_Bay', text: 'America/Thunder Bay (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Toronto', text: 'America/Toronto (EDT)' },
	{ group: 'UTC-04:00', timezone: 'America/Tortola', text: 'America/Tortola (AST)' },
	// UTC-05:00
	{ group: 'UTC-05:00', timezone: 'America/Atikokan', text: 'America/Atikokan (EST)' },
	{ group: 'UTC-05:00', timezone: 'America/Bahia_Banderas', text: 'America/Bahia Banderas (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Bogota', text: 'America/Bogota (-05)' },
	{ group: 'UTC-05:00', timezone: 'America/Cancun', text: 'America/Cancun (EST)' },
	{ group: 'UTC-05:00', timezone: 'America/Cayman', text: 'America/Cayman (EST)' },
	{ group: 'UTC-05:00', timezone: 'America/Chicago', text: 'America/Chicago (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Eirunepe', text: 'America/Eirunepe (-05)' },
	{ group: 'UTC-05:00', timezone: 'America/Guayaquil', text: 'America/Guayaquil (-05)' },
	{ group: 'UTC-05:00', timezone: 'America/Indiana/Knox', text: 'America/Indiana/Knox (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Indiana/Tell_City', text: 'America/Indiana/Tell City (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Jamaica', text: 'America/Jamaica (EST)' },
	{ group: 'UTC-05:00', timezone: 'America/Lima', text: 'America/Lima (-05)' },
	{ group: 'UTC-05:00', timezone: 'America/Matamoros', text: 'America/Matamoros (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Menominee', text: 'America/Menominee (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Merida', text: 'America/Merida (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Mexico_City', text: 'America/Mexico City (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Monterrey', text: 'America/Monterrey (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/North_Dakota/Beulah', text: 'America/North Dakota/Beulah (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/North_Dakota/Center', text: 'America/North Dakota/Center (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/North_Dakota/New_Salem', text: 'America/North Dakota/New Salem (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Panama', text: 'America/Panama (EST)' },
	{ group: 'UTC-05:00', timezone: 'America/Rainy_River', text: 'America/Rainy River (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Rankin_Inlet', text: 'America/Rankin Inlet (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Resolute', text: 'America/Resolute (CDT)' },
	{ group: 'UTC-05:00', timezone: 'America/Rio_Branco', text: 'America/Rio Branco (-05)' },
	{ group: 'UTC-05:00', timezone: 'America/Winnipeg', text: 'America/Winnipeg (CDT)' },
	// UTC-06:00
	{ group: 'UTC-06:00', timezone: 'America/Belize', text: 'America/Belize (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Boise', text: 'America/Boise (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Cambridge_Bay', text: 'America/Cambridge Bay (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Chihuahua', text: 'America/Chihuahua (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Costa_Rica', text: 'America/Costa Rica (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Denver', text: 'America/Denver (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Edmonton', text: 'America/Edmonton (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/El_Salvador', text: 'America/El Salvador (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Guatemala', text: 'America/Guatemala (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Inuvik', text: 'America/Inuvik (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Managua', text: 'America/Managua (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Mazatlan', text: 'America/Mazatlan (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Ojinaga', text: 'America/Ojinaga (MDT)' },
	{ group: 'UTC-06:00', timezone: 'America/Regina', text: 'America/Regina (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Swift_Current', text: 'America/Swift Current (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Tegucigalpa', text: 'America/Tegucigalpa (CST)' },
	{ group: 'UTC-06:00', timezone: 'America/Yellowknife', text: 'America/Yellowknife (MDT)' },
	{ group: 'UTC-06:00', timezone: 'Pacific/Easter', text: 'Pacific/Easter (-06)' },
	{ group: 'UTC-06:00', timezone: 'Pacific/Galapagos', text: 'Pacific/Galapagos (-06)' },
	// UTC-07:00
	{ group: 'UTC-07:00', timezone: 'America/Creston', text: 'America/Creston (MST)' },
	{ group: 'UTC-07:00', timezone: 'America/Dawson', text: 'America/Dawson (PDT)' },
	{ group: 'UTC-07:00', timezone: 'America/Dawson_Creek', text: 'America/Dawson Creek (MST)' },
	{ group: 'UTC-07:00', timezone: 'America/Fort_Nelson', text: 'America/Fort Nelson (MST)' },
	{ group: 'UTC-07:00', timezone: 'America/Hermosillo', text: 'America/Hermosillo (MST)' },
	{ group: 'UTC-07:00', timezone: 'America/Los_Angeles', text: 'America/Los Angeles (PDT)' },
	{ group: 'UTC-07:00', timezone: 'America/Phoenix', text: 'America/Phoenix (MST)' },
	{ group: 'UTC-07:00', timezone: 'America/Tijuana', text: 'America/Tijuana (PDT)' },
	{ group: 'UTC-07:00', timezone: 'America/Vancouver', text: 'America/Vancouver (PDT)' },
	{ group: 'UTC-07:00', timezone: 'America/Whitehorse', text: 'America/Whitehorse (PDT)' },
	// UTC-08:00
	{ group: 'UTC-08:00', timezone: 'America/Anchorage', text: 'America/Anchorage (AKDT)' },
	{ group: 'UTC-08:00', timezone: 'America/Juneau', text: 'America/Juneau (AKDT)' },
	{ group: 'UTC-08:00', timezone: 'America/Metlakatla', text: 'America/Metlakatla (AKDT)' },
	{ group: 'UTC-08:00', timezone: 'America/Nome', text: 'America/Nome (AKDT)' },
	{ group: 'UTC-08:00', timezone: 'America/Sitka', text: 'America/Sitka (AKDT)' },
	{ group: 'UTC-08:00', timezone: 'America/Yakutat', text: 'America/Yakutat (AKDT)' },
	{ group: 'UTC-08:00', timezone: 'Pacific/Pitcairn', text: 'Pacific/Pitcairn (-08)' },
	// UTC-09:00
	{ group: 'UTC-09:00', timezone: 'America/Adak', text: 'America/Adak (HDT)' },
	{ group: 'UTC-09:00', timezone: 'Pacific/Gambier', text: 'Pacific/Gambier (-09)' },
	// UTC-09:30
	{ group: 'UTC-09:30', timezone: 'Pacific/Marquesas', text: 'Pacific/Marquesas (-09:30)' },
	// UTC-10:00
	{ group: 'UTC-10:00', timezone: 'Pacific/Honolulu', text: 'Pacific/Honolulu (HST)' },
	{ group: 'UTC-10:00', timezone: 'Pacific/Rarotonga', text: 'Pacific/Rarotonga (-10)' },
	{ group: 'UTC-10:00', timezone: 'Pacific/Tahiti', text: 'Pacific/Tahiti (-10)' },
	// UTC-11:00
	{ group: 'UTC-11:00', timezone: 'Pacific/Midway', text: 'Pacific/Midway (SST)' },
	{ group: 'UTC-11:00', timezone: 'Pacific/Niue', text: 'Pacific/Niue (-11)' },
	{ group: 'UTC-11:00', timezone: 'Pacific/Pago_Pago', text: 'Pacific/Pago Pago (SST)' }
] as IanaTimezone[];
